(async () => {
  const page=document.body.dataset.page||'login',root=document.getElementById('app');
  const signedIn=window.LAUNCHOPS_AUTH.user;
  if(page!=='login'&&!signedIn){location.replace(`login.html?next=${encodeURIComponent(location.pathname+location.search)}`);return}
  if(page==='login'&&signedIn){location.replace('projects.html');return}
  const M=window.LAUNCHOPS_MOCK, V=window.LaunchValidation, key=`launchops-v1-${signedIn?.uid||'guest'}`;
  let state;try{state=JSON.parse(localStorage.getItem(key))||structuredClone(M)}catch{state=structuredClone(M)}
  const save=()=>localStorage.setItem(key,JSON.stringify(state));
  const qs=new URLSearchParams(location.search),currentKey=`launchops-current-${signedIn?.uid||'guest'}`,projectId=qs.get('project')||localStorage.getItem(currentKey)||state.projects[0].id;
  let project=state.projects.find(p=>p.id===projectId)||state.projects[0];
  const pid=()=>`?project=${encodeURIComponent(project.id)}`;
  const link=(file)=>`${file}.html${file==='projects'||file==='new-project'||file==='login'?'':pid()}`;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>`${Number(n||0).toLocaleString('ko-KR')}원`,num=n=>Number(n||0).toLocaleString('ko-KR');
  const badge=(s)=>`<span class="badge ${esc(s)}">${esc(V.statusLabels[s]||{connected:'연결됨',disconnected:'연결 안 됨',reconnect_required:'재연결 필요',draft:'초안',ready:'준비됨',running:'진행 중',completed:'완료',approved:'승인됨',scheduled:'예약됨',sent:'발송 성공',failed:'발송 실패'}[s]||s)}</span>`;
  const a=(name,file,kind='secondary')=>`<a class="button ${kind}" href="${link(file)}">${name}</a>`;
  const actions=(items)=>`<div class="actions">${items.join('')}</div>`;
  const card=(body,cls='')=>`<section class="card ${cls}">${body}</section>`;
  const field=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
  const area=(label,name,value='',rows=3)=>`<label class="field"><span>${label}</span><textarea name="${name}" rows="${rows}">${esc(value)}</textarea></label>`;
  const select=(label,name,items,selected)=>`<label class="field"><span>${label}</span><select name="${name}">${items.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;
  const metricSelect=(name,selected)=>`<label class="field"><span>지표</span><select name="${name}">${Object.entries(V.labels).map(([value,label])=>`<option value="${value}" ${value===selected?'selected':''}>${label}</option>`).join('')}</select></label>`;
  const notice=(text,type='info')=>`<div class="notice ${type}">${text}</div>`;
  function shell(title,subtitle,content,step){const nav=[['projects','프로젝트'],['dashboard','대시보드'],['new-experiment','새 실험'],['validation-result','검증 결과'],['pr-channels','PR 준비']];root.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="brand" href="projects.html"><span class="brand-mark">L</span><span>LaunchOps<small>Market validation</small></span></a><div class="sidebar-label">WORKSPACE</div><nav>${nav.map(([f,n])=>`<a href="${link(f)}" class="${page===f?'active':''}">${n}</a>`).join('')}</nav><div class="sidebar-foot">MOCK WORKSPACE<br><strong>${esc(project.name)}</strong><small>데이터는 이 브라우저에 저장됩니다.</small></div></aside><div class="main-wrap"><header class="topbar"><span>LaunchOps <span class="slash">/</span> ${esc(project.name)}</span><span class="topbar-right">${esc(signedIn.email)} <button type="button" class="logout-button" data-logout>로그아웃</button></span></header><main class="content">${step?`<div class="eyebrow">${step}</div>`:''}<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div></div>${content}</main></div></div>`}
  function formSubmit(id,fn){document.getElementById(id)?.addEventListener('submit',e=>{e.preventDefault();fn(new FormData(e.currentTarget))})}
  function go(file){location.href=link(file)}
  function current(){localStorage.setItem(currentKey,project.id)}
  async function logout(){await window.LAUNCHOPS_AUTH.signOut();location.replace('login.html')}
  root.addEventListener('click',event=>{if(event.target.closest('[data-logout]'))logout()});
  function result(){return V.evaluate(project)}
  function getExperiment(){const id=qs.get('experiment');return project.experiments.find(e=>e.id===id)||project.experiments[0]}
  const nextText={insufficient_evidence:'판정에 필요한 표본을 더 확보하세요.',learning:'현재 실험 결과를 계속 관찰하세요.',validated:'검증 근거를 바탕으로 PR을 준비할 수 있습니다.',invalidated:'고객군 또는 메시지를 바꿔 추가 실험을 진행하세요.'};
  function funnel(m){const rows=[['노출',m.impressions],['관심',m.engagements],['방문',m.landingSessions],['가입',m.signups],['활성화',m.activations],['결제',m.purchases]];return `<div class="funnel">${rows.map(([n,v],i)=>`<div class="funnel-row"><span>${n}</span><div class="track"><i style="width:${Math.max(4,Math.min(100,v/(m.impressions||1)*100*(i?2.2:1)))}%"></i></div><strong>${num(v)}</strong></div>`).join('')}</div>`}
  function metrics(m){return `<div class="metric-grid">${[['노출',m.impressions],['관심',m.engagements],['클릭',m.clicks],['방문',m.landingSessions],['가입',m.signups],['활성화',m.activations],['결제',m.purchases]].map(([n,v])=>`<div class="metric"><span>${n}</span><strong>${num(v)}</strong></div>`).join('')}</div>`}
  function projectList(){root.innerHTML=`<div class="app-shell"><aside class="sidebar"><a class="brand" href="projects.html"><span class="brand-mark">L</span><span>LaunchOps<small>Market validation</small></span></a><div class="sidebar-label">WORKSPACE</div><nav><a class="active" href="projects.html">프로젝트</a><a href="new-project.html">새 프로젝트</a></nav><div class="sidebar-foot">MOCK WORKSPACE<small>데이터는 이 브라우저에 저장됩니다.</small></div></aside><div class="main-wrap"><header class="topbar">LaunchOps <span class="topbar-right">${esc(signedIn.email)} <button type="button" class="logout-button" data-logout>로그아웃</button></span></header><main class="content"><div class="page-heading spread"><div><div class="eyebrow">YOUR PROJECTS</div><h1>프로젝트</h1><p>제품별 시장검증 상태를 한곳에서 확인하세요.</p></div>${a('새 프로젝트 만들기','new-project','primary')}</div><div class="project-grid">${state.projects.map(p=>{const r=V.evaluate(p);return `<a class="card project-card" href="dashboard.html?project=${encodeURIComponent(p.id)}"><div class="project-icon">${esc(p.name[0])}</div><div class="project-top">${badge(r.status)}<span>${esc(p.category)}</span></div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="project-bottom"><span>Validation Score <strong>${r.score}</strong></span><span>업데이트 ${esc(p.updatedAt||'—')}</span></div></a>`}).join('')}</div></main></div></div>`}
  if(page==='login'){
    root.innerHTML=`<div class="login-page"><div class="login-decor"><span class="brand light"><span class="brand-mark">L</span><span>LaunchOps<small>Market validation</small></span></span><div><div class="eyebrow">BUILD → VALIDATE → GROW</div><h1>만든 제품의<br>다음 결정을<br>데이터로.</h1><p>노출부터 결제까지 이어지는 시장 반응을 한눈에 확인하세요.</p></div><div class="login-foot">LaunchOps</div></div><div class="login-panel"><div class="login-box"><div class="eyebrow">WELCOME TO LAUNCHOPS</div><h2>로그인</h2><p>Google 계정으로 프로젝트에 접속하세요.</p><button class="button primary wide" type="button" id="google-login"><span class="google-g">G</span> Google로 계속하기</button><p id="auth-error" class="auth-error" role="alert" hidden></p></div></div></div>`;
    document.getElementById('google-login').addEventListener('click',async event=>{const button=event.currentTarget,error=document.getElementById('auth-error');button.disabled=true;error.hidden=true;try{await window.LAUNCHOPS_AUTH.signIn();const next=qs.get('next');location.replace(/^\/[a-z-]+\.html(?:\?[a-zA-Z0-9=&_%.-]*)?$/.test(next||'')?next:'projects.html')}catch(failure){const messages={'auth/popup-closed-by-user':'Google 로그인 창이 닫혔습니다.','auth/popup-blocked':'팝업이 차단되었습니다. 브라우저에서 팝업을 허용해 주세요.','auth/unauthorized-domain':'현재 도메인이 Firebase Authentication의 승인된 도메인에 없습니다.','auth/operation-not-allowed':'Firebase Authentication에서 Google 로그인을 활성화해 주세요.','auth/network-request-failed':'네트워크 연결을 확인해 주세요.','auth/account-exists-with-different-credential':'같은 이메일의 다른 로그인 방식 계정이 있습니다.'};error.textContent=messages[failure.code]||'Google 로그인에 실패했습니다. 잠시 후 다시 시도해 주세요.';error.hidden=false;button.disabled=false}});
  }else if(page==='projects'){projectList()}
  else if(page==='new-project'){
    shell('새 제품 등록','검증할 제품의 기본 정보를 입력하세요.',`<div class="narrow">${card(`<form id="project-form" class="form-stack">${field('제품명','name','','text','required')}${field('제품 URL','url','','url','required placeholder="https://"')}<div class="form-grid">${field('카테고리','category','','text','required placeholder="예: Micro SaaS"')}${field('목표 시장','targetMarket','','text','required placeholder="예: 1인 창업자"')}</div>${area('제품 설명','description','',5)}${actions([a('목록으로','projects'),'<button class="button primary" type="submit">제품 분석 및 가설 생성</button>'])}</form>`)}</div>`,'01 / 제품 등록');
    formSubmit('project-form',f=>{const id='project-'+Date.now();project={id,name:String(f.get('name')).trim(),url:String(f.get('url')).trim(),category:String(f.get('category')).trim(),targetMarket:String(f.get('targetMarket')).trim(),description:String(f.get('description')).trim(),updatedAt:new Date().toLocaleString('ko-KR'),hypothesis:{audience:String(f.get('targetMarket')).trim()||'초기 사용자',problem:'고객이 현재 해결하기 어려운 문제를 확인합니다.',value:'제품이 문제 해결에 주는 가치를 확인합니다.',message:`${String(f.get('name')).trim()}의 가치를 확인해 보세요.`},criteria:structuredClone(M.projects[0].criteria),experiments:[],pr:{status:'draft'}};state.projects.unshift(project);save();current();go('validation-setup')})
  }else if(page==='validation-setup'){
    const h=project.hypothesis||M.projects[0].hypothesis;
    shell('검증 가설과 기준','고객군과 성공 기준을 실험 전에 정합니다.',`${notice('아래 가설은 샘플로 제안되었습니다. 제품에 맞게 수정해 주세요.')}<form id="setup-form" class="form-stack">${card(`<h2>검증 가설</h2><div class="form-grid">${field('고객군','audience',h.audience,'text','required')}${field('고객 문제','problem',h.problem,'text','required')}</div>${field('핵심 가치제안','value',h.value,'text','required')}${area('테스트 메시지','message',h.message)}`)}${card(`<div class="section-heading"><div><h2>검증 기준</h2><p>각 기준의 목표와 최소 표본을 직접 조정할 수 있습니다.</p></div></div><div class="criteria-list">${project.criteria.map((c,i)=>`<div class="criteria-item"><strong>기준 ${i+1}</strong><div class="criteria-fields">${metricSelect(`metric-${i}`,c.metric)}${select('비교',`operator-${i}`,['>=','<='],c.operator)}${field('목표 %',`target-${i}`,c.target,'number','min="0" step="0.1" required')}${field('최소 표본',`sample-${i}`,c.minimumSample,'number','min="0" required')}${field('가중치',`weight-${i}`,c.weight,'number','min="0" required')}<label class="check-field"><input type="checkbox" name="required-${i}" ${c.required?'checked':''}> 필수 기준</label></div></div>`).join('')}</div>`)}${actions([a('이전','new-project'),'<button class="button primary" type="submit">저장하고 채널 연결로</button>'])}</form>`,'02 / 검증 설정');
    formSubmit('setup-form',f=>{project.hypothesis={audience:f.get('audience'),problem:f.get('problem'),value:f.get('value'),message:f.get('message')};project.criteria=project.criteria.map((c,i)=>({...c,metric:f.get(`metric-${i}`),operator:f.get(`operator-${i}`),target:Number(f.get(`target-${i}`)),minimumSample:Number(f.get(`sample-${i}`)),weight:Number(f.get(`weight-${i}`)),required:f.has(`required-${i}`)}));project.updatedAt=new Date().toLocaleString('ko-KR');save();go('integrations')})
  }else if(page==='integrations'){
    shell('채널 연결','검증에 사용할 채널의 데모 연결 상태를 관리합니다.',`${notice('연결 버튼은 화면 상태만 바꿉니다. 외부 계정에는 접근하지 않습니다.')}<div class="integration-list">${['Meta','YouTube','Reddit'].map((name,i)=>card(`<div class="integration-row"><div class="channel-logo ${name.toLowerCase()}">${name[0]}</div><div class="grow"><h2>${name}</h2><p>권한 상태: ${state.integrations[name]==='connected'?'데모 연결 허용':state.integrations[name]==='reconnect_required'?'재연결 필요':'연결 전'} · 마지막 동기화: ${state.integrations[name]==='connected'?'2026-09-28 09:30':'—'}</p></div>${badge(state.integrations[name])}<button class="button secondary" data-channel="${name}">${state.integrations[name]==='connected'?'연결 해제':state.integrations[name]==='reconnect_required'?'재연결':'연결'}</button></div>`)).join('')}</div>${actions([a('이전','validation-setup'),a('실험 만들기','new-experiment','primary')])}`,'03 / 채널 연결');
    root.querySelectorAll('[data-channel]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.channel;state.integrations[name]=state.integrations[name]==='connected'?'disconnected':'connected';save();location.reload()}))
  }else if(page==='new-experiment'){
    const today=new Date().toISOString().slice(0,10);
    shell('새 검증 실험','고객군, 메시지, 채널과 예산을 정하고 실행을 승인하세요.',`<div class="two-column"><form id="experiment-form" class="form-stack">${card(`<div class="form-grid">${select('고객군','audience',[project.hypothesis.audience,'초기 스타트업 팀','프리랜서'],project.hypothesis.audience)}${select('채널','channel',['Meta','YouTube','Reddit'],'Meta')}</div>${select('테스트 메시지','message',[project.hypothesis.message,'지금 제품의 가치를 확인해 보세요.'],project.hypothesis.message)}<div class="form-grid">${field('예산 (원)','budget',100000,'number','min="0" required')}${field('Attribution 기간 (일)','attributionDays',7,'number','min="1" required')}${field('시작일','start',today,'date','required')}${field('종료일','end',today,'date','required')}</div>${actions([a('이전','integrations'),'<button class="button primary" type="submit">실행 승인</button>'])}</form>`)}</form><div>${card(`<h2>테스트 소재 미리보기</h2><div class="preview"><div class="preview-visual"><svg viewBox="0 0 300 140" role="img" aria-label="이미지 플레이스홀더"><rect width="300" height="140" rx="10" fill="#dcece9"/><circle cx="74" cy="57" r="20" fill="#a7d4cc"/><path d="M28 112l63-51 47 39 36-24 92 36" fill="none" stroke="#75b6a8" stroke-width="14" stroke-linecap="round"/></svg></div><strong id="preview-message">${esc(project.hypothesis.message)}</strong><span>${esc(project.name)} · <span id="preview-channel">Meta</span></span></div><div class="divider"></div><div class="summary-row"><span>예상 비용</span><strong id="cost-preview">100,000원</strong></div><p class="muted">승인해도 실제 광고가 집행되지 않습니다.</p>`)}</div></div>`,'04 / 실험 구성');
    const form=document.getElementById('experiment-form');form.addEventListener('input',()=>{document.getElementById('preview-message').textContent=form.elements.message.value;document.getElementById('preview-channel').textContent=form.elements.channel.value;document.getElementById('cost-preview').textContent=money(form.elements.budget.value)});
    formSubmit('experiment-form',f=>{if(String(f.get('end'))<String(f.get('start'))){alert('종료일은 시작일 이후여야 합니다.');return}project.experiments.unshift({id:'experiment-'+Date.now(),audience:f.get('audience'),message:f.get('message'),channel:f.get('channel'),budget:Number(f.get('budget')),start:f.get('start'),end:f.get('end'),attributionDays:Number(f.get('attributionDays')),status:'running',updatedAt:'데모 데이터 · 방금 승인',metrics:{impressions:0,engagements:0,clicks:0,landingSessions:0,signups:0,activations:0,purchases:0,spend:0}});project.updatedAt=new Date().toLocaleString('ko-KR');save();go('dashboard')})
  }else if(page==='dashboard'){
    const r=result(),m=r.metrics,latest=project.experiments[0],best=project.experiments.filter(e=>e.metrics?.landingSessions).sort((a,b)=>(b.metrics.signups/(b.metrics.landingSessions||1))-(a.metrics.signups/(a.metrics.landingSessions||1)))[0]||latest;
    shell(`${esc(project.name)} 대시보드`,'현재 시장검증 상태와 다음 행동을 확인하세요.',`<div class="hero-status">${card(`<div class="eyebrow">CURRENT VALIDATION</div><div class="status-line">${badge(r.status)}<h2>${V.statusLabels[r.status]}</h2></div><p>${nextText[r.status]}</p>${actions([a('검증 결과 자세히','validation-result','primary'),a('프로젝트 목록','projects')])}`,'status-card')}${card(`<div class="eyebrow">VALIDATION SCORE</div><div class="score">${r.score}<span>/ 100</span></div><div class="progress"><i style="width:${r.score}%"></i></div><p>기준 진행률 · ${r.passed}/${r.total}개 충족</p>`,'score-card')}</div><div class="three-grid">${[['고객군',best?.audience||project.hypothesis.audience],['메시지',best?.message||project.hypothesis.message],['채널',best?.channel||'—']].map(([n,v])=>card(`<span class="eyebrow">가장 반응 좋은 ${n}</span><h3>${esc(v)}</h3>`)).join('')}</div><div class="two-column">${card(`<div class="section-heading"><h2>다음 행동</h2>${a('새 실험','new-experiment')}</div><p>${nextText[r.status]}</p><div class="divider"></div><h2>핵심 퍼널</h2>${funnel(m)}`)}${card(`<div class="section-heading"><h2>최근 실험</h2>${a('전체 결과','experiment-detail')}</div>${project.experiments.length?project.experiments.map(e=>`<a class="list-row" href="experiment-detail.html?project=${encodeURIComponent(project.id)}&experiment=${encodeURIComponent(e.id)}"><span><strong>${esc(e.channel)} · ${esc(e.audience)}</strong><small>${esc(e.start)} ~ ${esc(e.end)}</small></span>${badge(e.status)}</a>`).join(''):'<p class="muted">아직 실험이 없습니다.</p>'}<div class="divider"></div><h2>PR 준비</h2><p>${r.status==='validated'?'검증 결과를 바탕으로 PR 문서를 준비할 수 있습니다.':'검증 결과를 확인하고 PR 준비 상태를 살펴보세요.'}</p>${a('PR 채널 보기','pr-channels')}`)}</div>`,'검증 대시보드');
  }else if(page==='experiment-detail'){
    const e=getExperiment();if(!e){shell('실험 상세','아직 실험이 없습니다.',actions([a('새 실험 만들기','new-experiment','primary')]),'실험');return}const m=e.metrics;
    shell('실험 상세',`${esc(e.channel)} · ${esc(e.audience)} · ${esc(e.start)} ~ ${esc(e.end)}`,`<div class="summary-strip"><span>상태 ${badge(e.status)}</span><span>예산 <strong>${money(e.budget)}</strong></span><span>실제 지출 <strong>${money(m.spend)}</strong></span><span>갱신 <strong>${esc(e.updatedAt)}</strong></span></div>${card(`<h2>성과 지표</h2>${metrics(m)}`)}<div class="two-column">${card(`<h2>전환 퍼널</h2>${funnel(m)}`)}${card(`<h2>실험 정보</h2><dl class="detail-list"><div><dt>고객군</dt><dd>${esc(e.audience)}</dd></div><div><dt>메시지</dt><dd>${esc(e.message)}</dd></div><div><dt>채널</dt><dd>${esc(e.channel)}</dd></div><div><dt>Attribution 기간</dt><dd>${num(e.attributionDays)}일</dd></div></dl>`)}</div>${card(`<h2>고객군·메시지·채널 비교</h2><div class="table-wrap"><table><thead><tr><th>실험 / 고객군</th><th>메시지</th><th>채널</th><th>방문</th><th>가입</th><th>가입률</th></tr></thead><tbody>${project.experiments.map(x=>`<tr><td>${esc(x.audience)}</td><td>${esc(x.message)}</td><td>${esc(x.channel)}</td><td>${num(x.metrics.landingSessions)}</td><td>${num(x.metrics.signups)}</td><td>${V.measure('signupRate',x.metrics).value.toFixed(1)}%</td></tr>`).join('')}</tbody></table></div>`)}${actions([a('대시보드','dashboard'),a('추가 실험','new-experiment'),a('검증 결과','validation-result','primary')])}`,'실험 분석');
  }else if(page==='validation-result'){
    const r=result(),best=project.experiments.filter(e=>e.metrics?.landingSessions).sort((a,b)=>(b.metrics.signups/(b.metrics.landingSessions||1))-(a.metrics.signups/(a.metrics.landingSessions||1)))[0];
    shell('검증 결과','설정한 기준과 실제 샘플 데이터를 비교한 판정입니다.',`${card(`<div class="result-head"><div><div class="eyebrow">FINAL DECISION</div><h2>${V.statusLabels[r.status]}</h2><p>${nextText[r.status]}</p></div><div class="result-score"><strong>${r.score}</strong><span>Validation Score</span></div></div><div class="summary-strip"><span>신뢰 수준 <strong>${r.confidence}</strong></span><span>표본 상태 <strong>${r.criteria.filter(c=>c.sample>=c.minimumSample).length}/${r.total}개 충족</strong></span><span>통과 기준 <strong>${r.passed}/${r.total}개</strong></span></div>`)}${card(`<h2>기준별 판정과 계산 근거</h2><div class="table-wrap"><table><thead><tr><th>지표</th><th>현재값</th><th>목표</th><th>표본 / 최소</th><th>가중치</th><th>결과</th></tr></thead><tbody>${r.criteria.map(c=>`<tr><td>${V.labels[c.metric]} ${c.required?'<small class="required">필수</small>':''}</td><td>${c.value.toFixed(1)}%</td><td>${esc(c.operator)} ${num(c.target)}%</td><td>${num(c.sample)} / ${num(c.minimumSample)}</td><td>${num(c.weight)}</td><td>${c.sample<c.minimumSample?badge('insufficient_evidence'):c.passed?'<span class="positive">통과</span>':'<span class="negative">미달</span>'}</td></tr>`).join('')}</tbody></table></div><p class="muted">점수 = 각 지표의 목표 대비 진행률(최대 100%) × 가중치의 합 ÷ 가중치 합. 최소 표본과 필수 기준을 별도로 판정합니다.</p>`)}<div class="two-column">${card(`<h2>Evidence</h2>${metrics(r.metrics)}<p class="muted">Mock 실험의 합계입니다. 실제 채널 데이터는 연결되지 않았습니다.</p>`)}${card(`<h2>다음 결정</h2><dl class="detail-list"><div><dt>가장 강한 고객군</dt><dd>${esc(best?.audience||'아직 없음')}</dd></div><div><dt>가장 강한 메시지</dt><dd>${esc(best?.message||'아직 없음')}</dd></div><div><dt>다음 권장 실험</dt><dd>${esc(nextText[r.status])}</dd></div><div><dt>PR에 활용할 주장</dt><dd>${r.status==='validated'?`${num(r.metrics.signups)}명 가입, ${num(r.metrics.activations)}명 활성화가 확인되었습니다.`:'검증 통과 후 수치 기반 주장 사용 가능'}</dd></div></dl>`)} </div>${actions([a('대시보드','dashboard'),a('추가 실험','new-experiment'),a('PR 채널 관리','pr-channels','primary')])}`,'검증 결과');
  }else if(page==='pr-channels'){
    function draw(){const q=document.getElementById('channel-search')?.value.toLowerCase()||'',filter=document.getElementById('channel-filter')?.value||'전체';const rows=state.prChannels.filter(c=>(filter==='전체'||c.type===filter)&&[c.name,c.topic,c.region].join(' ').toLowerCase().includes(q));document.getElementById('channels-body').innerHTML=rows.map(c=>`<tr><td><input type="checkbox" data-select="${esc(c.id)}" ${c.selected?'checked':''} ${c.excluded?'disabled':''}></td><td><strong>${esc(c.name)}</strong><small>${esc(c.topic)}</small></td><td>${esc(c.type)}</td><td>${esc(c.region)}</td><td>${esc(c.contact||'—')}<small>${esc(c.url||'—')}</small></td><td>${esc(c.language)}</td><td>${esc(c.lastContact)}</td><td>${esc(c.relation)}</td><td><input type="checkbox" data-exclude="${esc(c.id)}" ${c.excluded?'checked':''}></td><td><button class="text-button" data-edit="${esc(c.id)}">수정</button></td></tr>`).join('')||'<tr><td colspan="10">검색 결과가 없습니다.</td></tr>'}
    shell('PR 채널 관리','제품에 맞는 발송 대상을 선택하고 관리하세요.',`${card(`<div class="section-heading"><div><h2>채널 목록</h2><p>Mock 채널 데이터입니다.</p></div><button class="button primary" id="add-channel">채널 추가</button></div><div class="filter-row"><input id="channel-search" placeholder="채널명·주제·지역 검색" aria-label="채널 검색"><select id="channel-filter" aria-label="유형 필터"><option>전체</option><option>뉴스레터</option><option>커뮤니티</option><option>언론사</option></select></div><div class="table-wrap"><table><thead><tr><th>선택</th><th>채널명 / 주제</th><th>유형</th><th>지역</th><th>연락처 / URL</th><th>언어</th><th>최근 접촉</th><th>관계</th><th>제외</th><th></th></tr></thead><tbody id="channels-body"></tbody></table></div>`)}${actions([a('검증 결과','validation-result'),a('보도자료 작성','release-editor','primary')])}<dialog id="channel-dialog"><form id="channel-form" class="form-stack"><h2 id="dialog-title">채널 추가</h2><input type="hidden" name="id">${field('채널명','name','','text','required')}<div class="form-grid">${select('유형','type',['뉴스레터','커뮤니티','언론사'],'뉴스레터')}${field('주제','topic')}${field('지역','region')}${field('선호 언어','language','한국어')}</div>${field('연락처','contact')}${field('제출 URL','url','','url')}${field('최근 접촉','lastContact','—')}${field('관계 상태','relation','신규')}${actions(['<button class="button secondary" type="button" id="close-dialog">취소</button>','<button class="button primary" type="submit">저장</button>'])}</form></dialog>`,'PR 준비');draw();document.getElementById('channel-search').oninput=draw;document.getElementById('channel-filter').onchange=draw;
    const dialog=document.getElementById('channel-dialog'),form=document.getElementById('channel-form');document.getElementById('add-channel').onclick=()=>{form.reset();form.elements.id.value='';dialog.showModal()};document.getElementById('close-dialog').onclick=()=>dialog.close();root.addEventListener('click',e=>{const id=e.target.dataset.edit;if(!id)return;const c=state.prChannels.find(x=>x.id===id);Object.keys(c).forEach(k=>{if(form.elements[k])form.elements[k].value=c[k]});dialog.showModal()});root.addEventListener('change',e=>{const id=e.target.dataset.select||e.target.dataset.exclude;if(!id)return;const c=state.prChannels.find(x=>x.id===id);if(e.target.dataset.select)c.selected=e.target.checked;else {c.excluded=e.target.checked;if(c.excluded)c.selected=false}save();draw()});formSubmit('channel-form',f=>{const id=f.get('id')||'pr-'+Date.now(),old=state.prChannels.find(c=>c.id===id),c={id,name:f.get('name'),type:f.get('type'),topic:f.get('topic'),region:f.get('region'),language:f.get('language'),contact:f.get('contact'),url:f.get('url'),lastContact:f.get('lastContact'),relation:f.get('relation'),selected:old?.selected??true,excluded:old?.excluded??false};if(old)Object.assign(old,c);else state.prChannels.push(c);save();dialog.close();draw()})
  }else if(page==='release-editor'){
    const r=result();if(!project.pr.ko){project.pr.ko={title:`${project.name}, 초기 시장 반응 확인`,summary:`${project.name}의 시장검증 결과를 소개합니다.`,body:`${project.description} 샘플 검증 데이터에서 ${num(r.metrics.signups)}명 가입과 ${num(r.metrics.activations)}명 활성화가 확인되었습니다.`,company:`${project.name}은 ${project.targetMarket}을 위한 제품입니다.`,contact:'hello@example.com'};project.pr.en={title:`${project.name} shows early market response`,summary:`A sample validation update from ${project.name}.`,body:`${project.name} recorded ${num(r.metrics.signups)} signups and ${num(r.metrics.activations)} activations in mock experiments.`,company:`${project.name} serves ${project.targetMarket}.`,contact:'hello@example.com'};save()}
    let lang='ko';const selected=()=>state.prChannels.filter(c=>c.selected&&!c.excluded);
    shell('보도자료 · 피치 작성','검증 근거를 확인하고 배포할 문구를 수정하세요.',`<div class="editor-toolbar"><div class="eyebrow">MOCK PR DRAFT</div><div class="segmented"><button id="lang-ko" class="active" type="button">한국어</button><button id="lang-en" type="button">English</button></div></div><div class="two-column editor-layout"><form id="release-form" class="form-stack">${card(`<div id="editor-fields"></div>${actions([a('PR 채널','pr-channels'),'<button class="button primary" type="submit">배포 준비 완료</button>'])}`)}</form><div>${card(`<h2>검증 수치와 Evidence</h2><div class="metric-grid compact"><div class="metric"><span>가입</span><strong>${num(r.metrics.signups)}</strong></div><div class="metric"><span>활성화</span><strong>${num(r.metrics.activations)}</strong></div><div class="metric"><span>결제</span><strong>${num(r.metrics.purchases)}</strong></div></div>${a('검증 결과 보기','validation-result')}`)}${card(`<h2>미디어 자산</h2><div class="asset-placeholder"><svg viewBox="0 0 240 110" aria-label="미디어 자산 플레이스홀더"><rect width="240" height="110" rx="10" fill="#e5eeec"/><circle cx="65" cy="42" r="14" fill="#b8d7d0"/><path d="M20 90l60-45 42 32 30-22 65 35" fill="none" stroke="#9ac9bd" stroke-width="11" stroke-linecap="round"/></svg></div><p class="muted">샘플 이미지 플레이스홀더</p>`)}${card(`<h2>채널별 개인화 피치</h2><div id="pitch-preview"></div>`)}</div></div>`,'PR 콘텐츠');
    const renderEditor=()=>{const p=project.pr[lang];document.getElementById('editor-fields').innerHTML=`${select('PR 주제','topic',[...new Set(state.prChannels.map(c=>c.topic))],project.pr.topic||state.prChannels[0]?.topic)}${field('제목','title',p.title,'text','required')}${area('요약','summary',p.summary,3)}${area('본문','body',p.body,7)}${area('회사 소개','company',p.company,3)}${field('연락처','contact',p.contact,'text','required')}`;document.getElementById('pitch-preview').innerHTML=selected().map(c=>`<div class="pitch"><strong>${esc(c.name)}</strong><p>${esc(p.title)} — ${esc(c.topic)} 독자에게 ${esc(project.name)}의 검증 결과를 소개합니다.</p></div>`).join('')||'<p class="muted">선택된 채널이 없습니다.</p>';document.getElementById('lang-ko').classList.toggle('active',lang==='ko');document.getElementById('lang-en').classList.toggle('active',lang==='en')};const persist=()=>{const f=new FormData(document.getElementById('release-form'));project.pr.topic=f.get('topic');project.pr[lang]={title:f.get('title'),summary:f.get('summary'),body:f.get('body'),company:f.get('company'),contact:f.get('contact')};save()};renderEditor();['ko','en'].forEach(code=>document.getElementById('lang-'+code).onclick=()=>{persist();lang=code;renderEditor()});formSubmit('release-form',()=>{persist();project.pr.status='ready';save();go('distribution-results')})
  }else if(page==='distribution-results'){
    const d=project.distribution||(project.distribution=structuredClone(M.distribution)),recipients=state.prChannels.filter(c=>c.selected&&!c.excluded),excluded=state.prChannels.filter(c=>c.excluded),dupes=recipients.filter((c,i)=>c.contact&&recipients.findIndex(x=>x.contact===c.contact)!==i);save();
    shell('배포 승인 · 성과','수신자와 내용을 검토한 뒤 Mock 배포를 승인하세요.',`${notice('최종 승인 시 실제 메일이나 게시물이 발송되지 않습니다. 화면 상태만 바뀝니다.')}<div class="two-column">${card(`<h2>배포 대상 ${recipients.length}곳</h2>${recipients.map(c=>`<div class="list-row"><span><strong>${esc(c.name)}</strong><small>${esc(c.contact||c.url||'연락처 없음')}</small></span><span>${esc(c.language)}</span></div>`).join('')||'<p class="muted">선택한 채널이 없습니다.</p>'}<div class="divider"></div><p>발송 제외: ${excluded.length}곳 · 중복 연락처 경고: ${dupes.length}건</p>${dupes.length?notice('동일한 연락처가 여러 채널에 선택되어 있습니다.','warning'):''}`)}${card(`<h2>채널별 피치 미리보기</h2>${recipients.map(c=>`<div class="pitch"><strong>${esc(c.name)}</strong><p>${esc((project.pr[c.language==='영어'?'en':'ko']||project.pr.ko)?.title||'초안이 없습니다.')}</p></div>`).join('')||'<p class="muted">미리볼 채널이 없습니다.</p>'}`)}</div>${card(`<div class="section-heading"><h2>최종 승인</h2>${badge(d.status)}</div><form id="distribution-form" class="form-stack"><div class="radio-row"><label><input type="radio" name="mode" value="now" ${d.mode==='now'?'checked':''}> 즉시 배포</label><label><input type="radio" name="mode" value="schedule" ${d.mode==='schedule'?'checked':''}> 예약 배포</label></div>${field('예약 시간','scheduledAt',d.scheduledAt||'','datetime-local')}<p class="muted">승인은 데모 상태만 Approved 또는 Scheduled로 변경합니다.</p>${actions([a('문서 수정','release-editor'),'<button class="button primary" type="submit">최종 승인</button>'])}</form></div>`)}${card(`<h2>Mock 배포 결과와 성과</h2><div class="table-wrap"><table><thead><tr><th>채널</th><th>발송 상태</th><th>응답</th><th>기사화 링크</th><th>추천 방문</th><th>가입</th></tr></thead><tbody>${d.results.map(x=>`<tr><td>${esc(x.channel)}</td><td>${badge(x.status)}</td><td>${esc(x.reply)}</td><td>${x.article?`<a href="${esc(x.article)}" target="_blank" rel="noopener">샘플 링크 ↗</a>`:'—'}</td><td>${num(x.visits)}</td><td>${num(x.signups)}</td></tr>`).join('')}</tbody></table></div><p class="muted">결과 수치는 사전 입력된 샘플 데이터입니다.</p>`)}${actions([a('대시보드로','dashboard')])}`,'PR 배포');
    formSubmit('distribution-form',f=>{if(!recipients.length){alert('먼저 발송할 채널을 선택하세요.');return}if(f.get('mode')==='schedule'&&!f.get('scheduledAt')){alert('예약 시간을 선택하세요.');return}d.mode=f.get('mode');d.scheduledAt=f.get('scheduledAt');d.status=d.mode==='schedule'?'scheduled':'approved';project.pr.status=d.status;save();location.reload()})
  }
})();
