/* All sample content lives here. Replace these objects when real data is connected. */
window.LAUNCHOPS_MOCK = {
  projects: [
    {id:'project-001',name:'FlowNote',url:'https://example.com',category:'Micro SaaS',targetMarket:'1인 창업자',description:'고객 인터뷰 기록을 한곳에 모으는 도구',updatedAt:'2026-09-28 09:30',hypothesis:{audience:'1인 창업자',problem:'고객 인터뷰 내용이 여러 문서에 흩어져 있다.',value:'인터뷰 기록을 빠르게 정리하고 인사이트를 찾는다.',message:'고객의 목소리를 한곳에서 정리하세요.'},criteria:[{metric:'ctr',operator:'>=',target:3,minimumSample:1000,required:false,weight:15},{metric:'signupRate',operator:'>=',target:8,minimumSample:100,required:true,weight:25},{metric:'activationRate',operator:'>=',target:40,minimumSample:30,required:true,weight:30},{metric:'purchaseRate',operator:'>=',target:10,minimumSample:10,required:true,weight:30}],experiments:[{id:'experiment-001',audience:'1인 창업자',message:'고객의 목소리를 한곳에서 정리하세요.',channel:'Meta',budget:250000,start:'2026-09-01',end:'2026-09-14',attributionDays:7,status:'completed',updatedAt:'2026-09-28 09:30',metrics:{impressions:12000,engagements:620,clicks:420,landingSessions:350,signups:38,activations:18,purchases:6,spend:180000}},{id:'experiment-002',audience:'초기 스타트업 팀',message:'인터뷰에서 다음 제품 결정을 찾으세요.',channel:'Reddit',budget:100000,start:'2026-09-15',end:'2026-09-22',attributionDays:7,status:'completed',updatedAt:'2026-09-28 09:30',metrics:{impressions:6400,engagements:340,clicks:230,landingSessions:205,signups:24,activations:12,purchases:3,spend:85000}}],pr:{status:'draft',ko:{title:'FlowNote, 고객 인터뷰를 제품 결정으로 연결하다',summary:'FlowNote가 초기 창업자의 고객 인터뷰 정리를 돕습니다.',body:'FlowNote는 흩어진 인터뷰 기록을 한곳에 모아 제품 의사결정을 돕습니다. 시장검증 실험에서 가입과 활성화 반응을 확인했습니다.',company:'FlowNote는 초기 팀의 고객 이해를 돕는 도구입니다.',contact:'hello@flownote.example'},en:{title:'FlowNote turns customer interviews into product decisions',summary:'FlowNote helps founders organize customer interviews.',body:'FlowNote brings scattered interview notes together and helps teams make product decisions. Sample validation experiments showed signup and activation interest.',company:'FlowNote helps early teams understand their customers.',contact:'hello@flownote.example'}}},
    {id:'project-002',name:'TinyInvoice',url:'https://example.org',category:'업무 도구',targetMarket:'프리랜서',description:'간단한 견적과 청구 관리 서비스',updatedAt:'2026-09-25 14:20',hypothesis:{audience:'프리랜서',problem:'청구서를 만드는 데 시간이 오래 걸린다.',value:'몇 분 안에 견적과 청구서를 보낸다.',message:'청구 업무를 더 간단하게.'},criteria:[{metric:'ctr',operator:'>=',target:3,minimumSample:1000,required:false,weight:15},{metric:'signupRate',operator:'>=',target:8,minimumSample:100,required:true,weight:25},{metric:'activationRate',operator:'>=',target:40,minimumSample:30,required:true,weight:30},{metric:'purchaseRate',operator:'>=',target:10,minimumSample:10,required:true,weight:30}],experiments:[{id:'experiment-003',audience:'프리랜서',message:'청구 업무를 더 간단하게.',channel:'YouTube',budget:80000,start:'2026-09-20',end:'2026-09-27',attributionDays:7,status:'completed',updatedAt:'2026-09-28 09:30',metrics:{impressions:380,engagements:54,clicks:22,landingSessions:19,signups:2,activations:1,purchases:0,spend:32000}}],pr:{status:'draft'}}
  ],
  integrations:{Meta:'connected',YouTube:'reconnect_required',Reddit:'disconnected'},
  prChannels:[
    {id:'pr-001',name:'스타트업 데일리',type:'뉴스레터',topic:'스타트업',region:'한국',contact:'editor@startupdaily.example',url:'https://example.com/submit',language:'한국어',lastContact:'2026-08-12',relation:'관심',excluded:false,selected:true},
    {id:'pr-002',name:'Product Makers',type:'커뮤니티',topic:'제품·창업',region:'글로벌',contact:'',url:'https://example.org/submit',language:'영어',lastContact:'—',relation:'신규',excluded:false,selected:true},
    {id:'pr-003',name:'Tech Letter',type:'언론사',topic:'기술',region:'한국',contact:'news@techletter.example',url:'',language:'한국어',lastContact:'2026-07-05',relation:'접촉',excluded:true,selected:false}
  ],
  distribution:{status:'draft',mode:'now',scheduledAt:'',results:[{channel:'스타트업 데일리',status:'sent',reply:'관심 있음',article:'https://example.com/article',visits:84,signups:9},{channel:'Product Makers',status:'failed',reply:'—',article:'',visits:0,signups:0}]}
};
