/* Criteria use percentages. Score is the weighted average of progress toward each target. */
window.LaunchValidation = (() => {
  const labels={ctr:'CTR',signupRate:'가입률',activationRate:'활성화율',purchaseRate:'결제 전환'};
  const ratio=(a,b)=>b>0?a/b*100:0;
  function aggregate(experiments){const keys=['impressions','engagements','clicks','landingSessions','signups','activations','purchases','spend'];return (experiments||[]).reduce((sum,e)=>{keys.forEach(k=>sum[k]+=(e.metrics?.[k]||0));return sum},Object.fromEntries(keys.map(k=>[k,0])))}
  function measure(metric,m){return {ctr:{value:ratio(m.clicks,m.impressions),sample:m.impressions},signupRate:{value:ratio(m.signups,m.landingSessions),sample:m.landingSessions},activationRate:{value:ratio(m.activations,m.signups),sample:m.signups},purchaseRate:{value:ratio(m.purchases,m.activations),sample:m.activations}}[metric]||{value:0,sample:0}}
  function evaluate(project){const metrics=aggregate(project.experiments);const criteria=(project.criteria||[]).map(c=>{const result=measure(c.metric,metrics),target=Number(c.target);const enough=result.sample>0&&result.sample>=Number(c.minimumSample);const passed=enough&& (c.operator==='<='?result.value<=target:result.value>=target);const progress=!enough?0:c.operator==='<='?(result.value<=target?100:(result.value?Math.min(100,target/result.value*100):0)):(target>0?Math.min(100,result.value/target*100):0);return {...c,...result,passed,progress}});const weight=criteria.reduce((n,c)=>n+Number(c.weight||0),0);const score=weight?Math.round(criteria.reduce((n,c)=>n+c.progress*Number(c.weight||0),0)/weight):0;const available=criteria.filter(c=>c.sample>0&&c.sample>=Number(c.minimumSample));let status='insufficient_evidence';if(available.length){if(available.length<criteria.length)status='learning';else if(criteria.every(c=>c.passed))status='validated';else status='invalidated'}return {metrics,criteria,score,status,passed:criteria.filter(c=>c.passed).length,total:criteria.length,confidence:available.length===criteria.length?'높음':available.length?'보통':'낮음'}}
  return {aggregate,measure,evaluate,labels,statusLabels:{insufficient_evidence:'근거 부족',learning:'학습 중',validated:'검증 통과',invalidated:'반증'}};
})();
